ArthurSonzogni/FTXUI

tutorial/build-with-nxxm.md

Hi @ArthurSonzogni,
Actually you need to write the dependency case sensitively. I could then properly compile and run the example project through nxxm as a lib consumer. (Examples or tests dirs are not scanned by default in consumption mode).
Cheers,

:wrench: fix nxxm deps file instructions as it is case sensitive.

---

src/ftxui/component/screen_interactive.cpp

Fixes compilation error for macOS Clang compiler.
> '/src/ftxui/component/screen_interactive.cpp:36:5: error: use of undeclared identifier 'quick_exit'
For some reason macOS cstdlib doesn't contain definition for quick_exit()

Fix compilation issue on macOS(CLang compiler) 

---

README.md
examples/component/homescreen.cpp
examples/component/toggle.cpp
include/ftxui/dom/elements.hpp
include/ftxui/dom/requirement.hpp
src/ftxui/dom/composite_decorator.cpp
src/ftxui/dom/dbox.cpp
src/ftxui/dom/flex.cpp
src/ftxui/dom/gauge.cpp
src/ftxui/dom/graph.cpp
src/ftxui/dom/hbox.cpp
src/ftxui/dom/hbox_test.cpp
src/ftxui/dom/hflow.cpp
src/ftxui/dom/size.cpp
src/ftxui/dom/text.cpp
src/ftxui/dom/vbox.cpp
src/ftxui/dom/vbox_test.cpp

Two new elements:
- flex_grow  : Expand the element to occupy free space.
- flex_shrink: Minimize the element leave away missing space.
flex = flex_grow | flex_shrink.
Other changes:
- hbox and vbox are now non flexible by default.
- the vtext element has been added to help writting tests.
- Many new tests.

Add flex_grow and flex_shrink.

---

src/ftxui/component/event.cpp

Simply removing the 'P' case the conversion works fine. I didn't get the intention behind this case so feel free to reject the pull request if this fix isn't suitable.

Fixed P conversion

---

CMakeLists.txt
src/ftxui/component/event_test.cpp

See https://github.com/ArthurSonzogni/FTXUI/issues/31
Due to a bug fixed by:
https://github.com/ArthurSonzogni/FTXUI/pull/32
the character 'P' was not correctly converted into event.

Add regression test for issue 31.

---

src/ftxui/screen/terminal.cpp

My environment doesn't have the variable COLORTERM set. Assigning nullptr to a std::string causes the following exception:
```
a terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
```

Fix crash on unset environment variable.

---

doc/mainpage.md

`PixelAt(10,10)` was outside of the Screen and there is no c'tor for Dimensions but a static `Create` method.

fix documentation example of Screen class

---

src/ftxui/screen/screen.cpp

I observed the problem, that stepping into the next line when printing a screen fills the terminal column with the previous background color:
My fix yields this:
This is my example code: 
```cpp
#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/screen.hpp>
#include <iostream>
int main(void) {
using namespace ftxui;
Element document = graph([](int x, int y){
std::vector<int> result(x, 0);
for (int i{0}; i < x; ++i) {
result[i] = ((3 * i) / 2) % y;
}
return result;
}) | color(Color::Red) | border | color(Color::Green) | bgcolor(Color::DarkBlue);
auto screen = Screen::Create(
Dimension::Fixed(80),
Dimension::Fixed(10)
);
Render(screen, document);
std::cout << screen.ToString() << '\n';
}
```
Btw. this library is really great! I love its API and power. I've been looking for a lib like …

reset pixel style for newline

---

CMakeLists.txt
ftxui-config.cmake.in

When using FTXUI in my own program with CMake after `find_package(ftxui)` I had to `find_package(Threads)` which indicated, that the cmake config scripts of ftxui didn't model that dependency. I modified the generation of the cmake scripts to yield that dependency.

add dependency to Threads into generated cmake config

---

include/ftxui/component/event.hpp
src/ftxui/component/event.cpp

Fixes warnings on `==` when comparing events
- Make special events const
- Add const to getters
- Add const to equality operator

Fix event const correctness

---

include/ftxui/component/input.hpp

- Cursor position is very well protected in the render function
- Making it public enables scenarios like
- Tab completion
- Inheritance for things like suggestions/previews with tab completion

Make input cursor position public state

---

CMakeLists.txt

Compilation failed if ftxui was used in projects that were not git repositories. Since, in CMakeLists.txt working directory to execute command was set as the parent directory and not the FTXUI project directory.
Changed the working directory variable to ${CMAKE_CURRENT_SOURCE_DIR}, so as to get the version of FTXUI and not that of parent project
Fixes issue #60

Fixed issue (#60) - Compilation failed in non-git projects

---

src/ftxui/screen/screen.cpp

I decided to replace the non-printable character with a `space` and continue over a hang or throwing an exception: a CPU-burning hang is not nice and the rest of the code seems to not use exceptions.

Fixed infinite loop in Screen::ToString() for non-printable chars

---

include/ftxui/screen/color.hpp

wingdi.h (included via Windows.h) defines an RGB macro that breaks
things. If a user really wants that macro in the same file as FTXUI they
can move the Windows.h include to after the inclusion of FTXUI's
headers.
Fixes #59

Work around Windows.h breaking the Color::RGB function

---

CMakeLists.txt
src/ftxui/dom/separator.cpp
src/ftxui/dom/text.cpp

This flag is used to find global functions defined without a previous
declaration. Usually it spots accidental globals, but in this case it
was just missing headers.
```
Element separator()
Element separator(Pixel)
Element text(std::wstring)
Element vtext(std::wstring)
```
are all declared in `ftxui/dom/elements.hpp` which was missing from
the includes in the .cpp-files where they were defined.

Build with -Wmissing-declarations

---

src/ftxui/component/screen_interactive.cpp

Text cursor is visible when I use `ScreenInteractive::Fullscreen()`. Not sure is it reproducible on Linux but that's the case on Windows. I was using menu example and changed only screen mode:
I assume that usage of alternative screen command resets cursor hiding. Swap of those commands fixed that issue:
Need to check alternative screen functionality, looks like it was affected

Swapped order of hidding cursor and setting alternative screen

---

CMakeLists.txt

`cl : Command line warning D9025 : overriding '/W3' with '/W4'`

Fix MSVC Warning D9025

---

src/ftxui/screen/terminal.cpp

```
\lib\ftxui\src\ftxui\screen\terminal.cpp:9: warning: "NOMINMAX" redefined
#define NOMINMAX
In file included frommingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/c++config.h:508,
from mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cstdlib:41,
from ftxui\src\ftxui\screen\terminal.cpp:5:
mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32/bits/os_defines.h:45: note: this is the location of the previous definition
#define NOMINMAX 1
```

Fix Windows mingw64 build warning "NOMINMAX" redefined

---

include/ftxui/screen/screen.hpp

Instead of storing all the booleans with 5 bytes, use a bit field.
The size of a Pixel has been reduced by 25%, from 20 byte to 15 bytes.

Compatify the Screen memory.

---

CMakeLists.txt

If we download the FTXUI source archive from the GitHub website, then the `.git` folder will be missing.
In such case, CMake configuration will fail:
> git found
> fatal: not a git repository (or any of the parent directories): .git
> CMake Error at CMakeLists.txt:21 (project):
>   VERSION "0.6." format invalid.

Set git_version when .git folder is missing

---

src/ftxui/component/screen_interactive.cpp

When SIGINT is intercepted, quit the run loop and raise the signal
again.
I am not sure this addresses:
https://github.com/ArthurSonzogni/FTXUI/issues/117
Maybe?

On SIGINT, raise signal again.

---

CMakeLists.txt
src/ftxui/component/component.cpp
src/ftxui/component/component_test.cpp

When switching from raw pointers toward shared_ptr, the destructor
wasn't updated correctly.
This patch:
- Fixes the issue.
- Add two regression tests.
- Use address sanitizer for the tests.
This fixes: https://github.com/ArthurSonzogni/FTXUI/issues/115

Fix ownership

---

src/ftxui/component/screen_interactive.cpp

A bug has been introduced in:
https://github.com/ArthurSonzogni/FTXUI/commit/478d7e8bcaea6a1afd94ea3053d4a3d495634ae2
I purposefully allowed raising the signal zero, because I thought this
was doing nothing. See the response:
https://stackoverflow.com/a/32260528/5112390
but this is different on Windows.
See:
https://github.com/ArthurSonzogni/FTXUI/issues/117

Fix bug with std::raise(0)

---

include/ftxui/screen/screen.hpp
src/ftxui/dom/text.cpp
src/ftxui/dom/text_test.cpp
src/ftxui/screen/screen.cpp

Modify the `ftxui::Pixel`. Instead of storing a `wchar_t`, store a
`std::wstring`. Now a single pixel can store multiple codepoints.
If a codepoint is of size <=0, it will be appended to the previous
pixel.
Only `ftxui::text()` is supported. `ftxui::vtext` support still needs to be
added.
This fixes: https://github.com/ArthurSonzogni/FTXUI/issues/109

Support combining characters.

---

CMakeLists.txt
cmake/ftxui_set_options.cmake
include/ftxui/component/checkbox.hpp
include/ftxui/component/radiobox.hpp
include/ftxui/component/screen_interactive.hpp
src/ftxui/component/checkbox.cpp
src/ftxui/component/component_test.cpp
src/ftxui/component/radiobox.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/frame.cpp
src/ftxui/dom/gauge.cpp
src/ftxui/dom/graph.cpp
src/ftxui/screen/terminal.cpp

Implement Fallback for microsoft's terminals.
I finally got access to a computer using the Microsoft's Windows OS.
That's the opportunity to find and mitigate all the problems
encountered. This patch:
1. Introduce an option and a C++ definition to enable fallback for
Microsoft's terminal emulators. This allows me to see/test the
Microsoft output from Linux. This also allows Windows users to remove
the fallback and target non Microsoft terminals on Windows if needed.
2. Microsoft's terminal suffer from a race condition bug when reporting
the cursor position:
https://github.com/microsoft/terminal/pull/7583.
The mitigation is not to ask for the cursor position in fullscreen
mode where it isn't really needed and request it less often.
This fixes: …

Implement Fallback for microsoft's terminals.

---

include/ftxui/component/component_base.hpp
src/ftxui/component/component.cpp
src/ftxui/component/component_test.cpp

If I create a Container with a list of children to be displayed and want to delete an entry, I would like to have a functionality corresponding to the add function. 
Furthermore, I added a begin/end function to ComponentBase to allow iteration over its children. The Remove function can then be conformant with vector::erase.

Allows components to remove a child or access to children in general

---

cmake/ftxui_benchmark.cmake
cmake/ftxui_set_options.cmake
cmake/ftxui_test.cmake
doc/mainpage.md
examples/component/CMakeLists.txt
examples/dom/CMakeLists.txt
examples/util/CMakeLists.txt

The `target_compile_features` command allows setting PUBLIC compile features for the library, making it implicit for the applications linking it. This reduces the CMake boilerplate required to set up a dependent project (eg. ftxui-starter).

Modify CMake usage to enable C++17

---

examples/component/homescreen.cpp
include/ftxui/component/screen_interactive.hpp
include/ftxui/dom/node.hpp
src/ftxui/component/container.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/blink.cpp
src/ftxui/dom/bold.cpp
src/ftxui/dom/clear_under.cpp
src/ftxui/dom/color.cpp
src/ftxui/dom/dim.cpp
src/ftxui/dom/frame.cpp
src/ftxui/dom/inverted.cpp
src/ftxui/dom/node_decorator.hpp
src/ftxui/dom/underlined.cpp
src/ftxui/screen/screen.cpp

**ContainerBase:**
- Extract Vertical, Horizontal and Tab containers to subclasses of ContainerBase.
- Preserve specific behaviour using virtual methods.
**NodeDecorator:**
- Collect the usage of `unpack` from NodeDecorator subclasses into single constructor.
**Miscellaneous:**
- Replace Graph functor in homescreen example with lambda.
- Reduce duplication of logic for Box Contains point from `Screen::PixelAt`.

Miscellaneous refactoring

---

include/ftxui/component/component_base.hpp
src/ftxui/component/component.cpp

- Invoke `DetachAllChildren` from `~ComponentBase`
- *Note: This reverses the order of Detach calls for children of the component. The previous order is not documented.*
- Define `Focused` using `Active`
- Compact `TakeFocus` loop code
- Add const for `Parent`, `Active` and `Focused`

Deduplicate logic in ComponentBase members

---

include/ftxui/dom/elements.hpp
include/ftxui/screen/screen.hpp
include/ftxui/screen/terminal.hpp
src/ftxui/dom/util.cpp
src/ftxui/screen/screen.cpp
src/ftxui/screen/terminal.cpp

- Convert `Dimension` to namespace to allow defining `Fit` method from dom.
- Use `Dimensions` extracted from `Terminal` as replacement `struct`.
- Convert `Terminal` to namespace as it only defines static members.
- Remove dom references from screen library (circular dependency).

Extract common struct Dimensions from Terminal

---

CMakeLists.txt
src/ftxui/dom/box_helper.cpp
src/ftxui/dom/box_helper.hpp
src/ftxui/dom/hbox.cpp
src/ftxui/dom/vbox.cpp

|hbox| and |vbox| are similar. They are just the same component, but
drawing in a different direction.
This patchs factorize the layout logic. Goal is to reduce code size and
reuse it for the |gridbox| dom element.
Bug: https://github.com/ArthurSonzogni/FTXUI/issues/114

Factorize box layout functions.

---

src/ftxui/component/input.cpp

Instead of wrapping WideInputBase by composition, wrap it by
inheritance. This resolve the focus that was broken.

Fix input.

---

src/ftxui/screen/screen.cpp

Screen::ApplyShader accounted for 60% of the computation. This patch
optimize it.
Performance on a 80x80 frame improved from 1400 draw/s to 7000 draw/s.

Optimize performance.

---

include/ftxui/component/component_options.hpp
src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp

- Password is now taking a ref, allowing a shared state to be used by
multiple passwords.
- Password cursor position is now optional. It will be used only when
set to something different from -1.

Update Input's options.

---

examples/dom/style_color.cpp
include/ftxui/screen/color.hpp
src/ftxui/screen/color.cpp

This is a little helper function I found myself longing for while using the library. It makes defining RGB colors in the common hex format quite convenient:
```c++
auto theme_carbon_grey90() -> theme
{
using namespace ftxui::literals;
return theme{.ui_background = 0x262626_rgb,
.interactive_01 = 0x0f'62'fe_rgb,
.interactive_02 = 0x6f'6f'6f_rgb,
```
In order to allow using the literal on its own it has been put into the
inline namespace `literals`.

Add an UDL for combined hex RGB colors

---

src/ftxui/dom/separator.cpp

It was removed by mistacke previously.
Take the opportunity to create new documentation.

Fix: Add separator(Pixel) back.

---

CHANGELOG.md
include/ftxui/screen/string.hpp
src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp
src/ftxui/screen/string.cpp
src/ftxui/screen/string_test.cpp

Use std::string by default for the implementation of FTXUI's input
component.
Along the way:
- Give a correct implementation for fullwidth characters.
- Add tests
- Modify the way the cursor is drawn.

Bugfix Input use std::string

---

include/ftxui/screen/screen.hpp
include/ftxui/util/ref.hpp

It's possible to mark some functions as `constexpr`.
Which leads to some memory changes and slight performance improvements

Constexpr support

---

CHANGELOG.md
include/ftxui/screen/screen.hpp
src/ftxui/dom/border.cpp
src/ftxui/dom/separator.cpp
src/ftxui/screen/screen.cpp

Add the `automerge` attribute to the Pixel bit field. It controls
whether two pixels must be automerged. Defining this allows two
mergeable characters not to be merged.
This was requested by:
https://github.com/ArthurSonzogni/FTXUI/issues/285

Automerge feature.

---

examples/component/with_restored_io.cpp
include/ftxui/dom/table.hpp
src/ftxui/component/checkbox.cpp
src/ftxui/component/component_fuzzer.cpp
src/ftxui/component/input.cpp
src/ftxui/component/menu.cpp
src/ftxui/component/radiobox.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/component/toggle.cpp
src/ftxui/dom/table.cpp

I've gotten a build error complaining about there being no `clamp` identifier in `std` namespace.
Snooping around showed me that `std::clamp` caused some issues and was replaced. These two lines were left out, this should fix my build issues and clean up the removal of `std::clamp`.
Also, `clang-format`-ed the source.

Replace std::clamp with util::clamp and reformat the code

---

include/ftxui/component/component.hpp
include/ftxui/util/ref.hpp

ftxui::Ref<> is used for passing Options, for instance, MenuOption,
to the corresponding component which is supposed to hold a strong
reference of it. and we can observe the events sent to the component
by setting callback(s) in the option instance passed to the owner
component.
but the callback function is not always copyable, despite that it
might be moveable.
in this change,
* Make<>() is updated to use the perfect forwarding to avoid
enforcing its parameters to be copyable.
* Ref<> is also updated to take a rvalue reference, so we can
move away from the contructor parameter when creating an
instance of Ref<>() from it.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

allow passing move-only parameter to Make()

---

CHANGELOG.md
cmake/ftxui_set_options.cmake

PREFIX is by default "lib", which most of the libraries use.
this changes makes the library files libftxui-foo.a
as ArthurSonzogni/FTXUI#140 intended originally

don't override PREFIX target property

---

CHANGELOG.md
src/ftxui/component/component.cpp
src/ftxui/component/component_test.cpp
src/ftxui/component/container.cpp
src/ftxui/component/container_test.cpp

- Provide better defaults for ComponentBase `Focusable()` and
`ActiveChild()` methods. This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/335
- Implement `Container::Tab` 's  `Focusable()` methods. This prevents
the users to navigate into a tab with no interactivity.

Improve ComponentBase and Container::Tab Focusable implementations

---

src/ftxui/dom/table.cpp

The table is not meant to be used to render more than once. Reset the
dimensions so that, even if it is used wrongly, this is not memory
unsafe.
This was raised by:
https://github.com/ArthurSonzogni/FTXUI/issues/381

Table: reset dimensions.

---

CHANGELOG.md
include/ftxui/screen/box.hpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/dbox.cpp
src/ftxui/dom/flexbox.cpp
src/ftxui/dom/flexbox_test.cpp
src/ftxui/dom/hbox.cpp
src/ftxui/dom/vbox.cpp
src/ftxui/screen/box.cpp
src/ftxui/screen/terminal.cpp

- Fix focus in flexbox. This required resetting the focus state at the
beginning of the ComputeRequirement(), because it can now run several
times.
This resolves:https://github.com/ArthurSonzogni/FTXUI/issues/399
- Add Box::Union.
- Add a preliminary implementation of forwarding selected_box from
within the flexbox.

Fix focus vs flexbox interaction.

---

.github/workflows/build.yaml

Related to https://github.com/aminya/setup-cpp/issues/86

ci: use gcovr 5.0 temporarily

---

CHANGELOG.md
src/ftxui/dom/canvas.cpp
src/ftxui/dom/canvas_test.cpp

width and height were being set using the incorrect axes resulting in incorrect canvas dimensions

Swap incorrect width/height mapping

---

cmake/ftxui_set_options.cmake

Sets the include directories as `SYSTEM INTERFACE` for users of this library to suppress compiler warnings in these header files (from e.g. -Weffc++).
To ensure that compiler warnings always appear when the project is opened stand-alone, I included a small check on the project name. This is not a perfect solution. If users of this library use FetchContent before setting their own project name, they will still get compiler warnings. However, I think it's an improvement.
I checked that the compiler warnings disappear in my other project when I FetchContent my fork, and that I still get compiler warnings when opening the fork as a stand-alone project.

Set includes as system interface to suppress warnings for other users

---

src/ftxui/screen/screen.cpp

Previously, a new 2D vector was allocated for every new frame. This
caused a lot of temporary allocation to be made.
This patch modify "Screen::Clear" so that it do make a new allocation,
but clear the existing one instead.
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/290#issuecomment-1153327251

Avoid making new allocation to clear the screen.

---

src/ftxui/dom/border.cpp
src/ftxui/dom/table.cpp

This for some reason caused the clang compiler to crash, while also
being incorrect as the tables are actually only 5x6.
See the LLVM issue here:
https://github.com/llvm/llvm-project/issues/56016
This patch was suggested by @tbaederr

Fix border charset array being to large

---

examples/component/homescreen.cpp

This addresses and fix:
https://github.com/ArthurSonzogni/FTXUI/issues/430
This patchs makes |shift| to be read and written on the same thread. We
request the update to be made via a task posted on the main thread.
This patch has no real consequence, the previous behavior was fine.
I hope it will help users not to have thread safety issue and better
understand they can post tasks this way.

Fix homescreen example thread safety.

---

doc/doxygen_extra.css
doc/mainpage.md

This PR solves #434 by improving on the existing introductory tutorial through adjustment of the grammar and vocabulary of the sentences, rewriting of sentences, writing new descriptions for sub-headings, and adding new link references for the corresponding discussion elements. 
I have not replaced the inline script ascii calls yet, and there might be a few other things that might require some adjustment. However, this version looks much cleaner, consistent, and descriptive that the previous iteration.

Improved Introductory Tutorial Page

---

src/ftxui/dom/canvas.cpp

Fix for Canvas::DrawText() draws nothing if the start coordinate is out of bounds.

Fixes #441

---

src/ftxui/screen/screen.cpp

One single reset code controls both the dim and bold properties. Mixing both led to one of the properties being wrongly reset.

Fixed dim and bold not mixing well

---

src/ftxui/dom/scroll_indicator.cpp

A divide by zero segfault would occur in vscroll_indicator if terminal window height was shrunk. Added conditional to prevent this from occurring.

Fixed divide by zero segault

---

src/ftxui/component/radiobox.cpp
src/ftxui/component/radiobox_test.cpp

Handled Space and Enter events for Radiobox, added tests for other event handling in radiobox. 
Is there any easy way to initialize `RadioboxBase::box_ ` in testing context? It is required to test PageUp, PageDown, Tab and TabReverse events.

#487 Handled Space and Enter events for Radiobox

---

src/ftxui/component/screen_interactive.cpp
src/ftxui/screen/screen.cpp
src/ftxui/screen/terminal.cpp

MinGW on Linux is case sensitive. Windows is case insensitive.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

fix cross compiling with MinGW

---

src/ftxui/screen/string.cpp

I could not build the library because std::ignore was not found.
https://en.cppreference.com/w/cpp/utility/tuple/ignore
Its in the \<tuple\> header. I added the include.

Fix std::ignore is in <tuple>.

---

include/ftxui/component/screen_interactive.hpp
src/ftxui/component/screen_interactive.cpp

There exists a possibility of a signal occurring during a Receiver::Receive(), while a lock is held on its mutex.  The lock is not released during the signal handler.  If we then redraw the screen inside the signal handler via the same Sender, then we try to acquire a lock on that same mutex, which effectively halts the program.
Let's move the code from inside the signal handler to outside of it.  A simple boolean flag should be fine.  We can then check for this flag in the ScreenInteractive's EventListener and perform the action there.
NOTE: The only reason this was noticed is because I changed my project's use of FTXUI from muti-threaded to a single-threaded, custom event loop.  Windows hasn't shown me this issue.

Improve UNIX signal handling of SIGWINCH

---

src/ftxui/component/screen_interactive.cpp

Windows output UTF16 unicode char, but FTXUI works using UTF8. Do the conversion.
This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/495

Fix Windows UTF16 char.

---

src/ftxui/component/container.cpp

This PR fixes a crash when a tab container is created with empty children. All other member functions already guard for this special case, but `OnMouseEvent` did not.

Fix crash on empty tab container

---

README.md

The vcpkg.info site is now defunct.
[vcpkgx.com](https://github.com/vcpkgx/vcpkgx.github.io) provides a similar if not identical service to what vcpkg.info used to provide.

Readme.md: change vcpk.info to vcpkgx.com

---

CHANGELOG.md
examples/dom/CMakeLists.txt
examples/dom/border_colored.cpp
include/ftxui/dom/elements.hpp
src/ftxui/dom/border.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/564

Add colored border.

---

flake.lock
flake.nix

Not sure if this will work, but basic example seems to be working.
Can you confirm that this lib has no dependencies and no absolute path.
Closes #598

Feature: Added nix build support

---

src/ftxui/component/collapsible.cpp
src/ftxui/component/maybe.cpp

Fixed wrong parameter documentation name.
Taken out of:
https://github.com/ArthurSonzogni/FTXUI/pull/600

Doc: Fix @params vs @param

---

cmake/ftxui_set_options.cmake

This makes FTXUI a better citizen for things like CPM, so that you can have consistent c++ standards settings across your dependencies.

Use globally set CMAKE_CXX_STANDARD, if it is set

---

src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser_test.cpp

Depending on the Cursor Key Mode (DECCKM), the terminal sends different escape sequences:
Key     Normal    Application
-----   --------  -----------
Up      ESC [ A   ESC O A
Down    ESC [ B   ESC O B
Right   ESC [ C   ESC O C
Left    ESC [ D   ESC O D
Home    ESC [ H   ESC O H
End     ESC [ F   ESC O F
I decided not to update the current mode to fit what FTXUI parse, but instead support parsing both. We convert the sequences from the "application mode" into the "normal mode".
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/626 Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/626

Support arrow keys in application mode.

---

CHANGELOG.md
include/ftxui/component/component_base.hpp

Delete copy constructor and copy operator to prevent odd behavior during object deletion. #637

Delete copy constructor and copy operator

---

src/ftxui/dom/canvas_test.cpp

Using `auto` seems to create a different output on different platforms. Notably it was observed that aarch64 compiles return a different value.
Fix the type of the characters iterated through the string.
Fixes #639

Fix types used in Hash() function used in tests.

---

src/ftxui/dom/linear_gradient.cpp

warning C4244: '=': conversion from '_Ty' to 'float', possible loss
of data
Looks like the rest of the file already writes "0" like this when assigning to LinearGradient types, so probably just an oversight.

Fix MSVC possible loss of data warning

---

cmake/ftxui_fuzzer.cmake
cmake/ftxui_set_options.cmake
cmake/ftxui_test.cmake
examples/CMakeLists.txt

As pointed out in https://github.com/ArthurSonzogni/FTXUI/pull/620#issuecomment-1555930977, compile_features is the proper way to set min C++ standard in CML of a project, specially for libraries.
Moreover compile features are propagated to CMake config file, unlike CXX_STANDARD property.
If needed, it can be overridden externally by users with CMAKE_CXX_STANDARD, which has precedence over compile feature.
I don't know exactly what is the minimum C++ standard of FTXUI libraries, tests, examples etc. There was CMAKE_CXX_STANDARD 20 for tests and fuzzers, and 17 for libraries and examples. I've assumed C++17 was the minimum standard of all targets, and I've set cxx_std_17 to all libraries and executables.

CMake: use compile_features to set min C++ standard

---

include/ftxui/screen/screen.hpp

This pull request changes the word 'codepoitns' to 'codepoints' on line 21 of screen.hpp.

Fix typo in 'codepoints' on line 21 of screen.hpp

---

src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser_test.cpp

Putty sends different escape sequences for F1-F4 keys than
other terminals do, so translate these variations.

Support F1-F4 from Putty

---

.clang-tidy
CHANGELOG.md
cmake/ftxui_test.cmake
examples/component/button_in_frame.cpp
examples/component/menu.cpp
examples/component/menu2.cpp
examples/component/menu_style.cpp
include/ftxui/component/component.hpp
include/ftxui/component/component_options.hpp
include/ftxui/screen/screen.hpp
include/ftxui/util/ref.hpp
src/ftxui/component/button.cpp
src/ftxui/component/checkbox.cpp
src/ftxui/component/collapsible.cpp
src/ftxui/component/component_options.cpp
src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp
src/ftxui/component/menu.cpp
src/ftxui/component/menu_test.cpp
src/ftxui/component/radiobox.cpp
src/ftxui/component/slider.cpp
src/ftxui/component/toggle_test.cpp
src/ftxui/dom/canvas.cpp
src/ftxui/dom/hyperlink.cpp
src/ftxui/screen/screen.cpp
src/ftxui/screen/string.cpp

Improve the overall interfaces.
1. Stop taking Ref<XxxOption> in Component constructors. Instead, use
the XxxOption directly. Passing by copy avoid problems developers had
where one was shared in between multiple component, causing issues.
2. Add variants of most component constructors taking a struct only.
This replaces:
https://github.com/ArthurSonzogni/FTXUI/pull/670
This fixes:
https://github.com/ArthurSonzogni/FTXUI/issues/426

Remove Ref<XxxOption> and add new interfaces.

---

examples/index.html
src/ftxui/dom/benchmark_test.cpp
src/ftxui/screen/string.cpp

Improve the performance of the functions for searching for codepoints in a table by passing the table array in as a reference instead of copying it.
This doesn't really improve the results of the benchmarks for some reason, but in my application with GCC8 i686, Intel Atom E3950 and a 180x60 terminal, this reduces the time for rendering a frame from ~31 ms to ~5.5 ms.

Improve unicode codepoint Bisearch performance

---

include/ftxui/screen/screen.hpp
src/ftxui/screen/screen.cpp

This PR addresses what we discussed in #700 by making the following changes:
- Add a const variant to the accessor functions
- Make Print and ToString functions const
- Move Doxygen comments to the header (I am happy to remove this change but I decided to kill two birds with one stone here)
This, when merged, should close #700

Improve const correctness in the Screen class

---

cmake/ftxui_find_google_benchmark.cmake

This upgrades the version of google benchmark used. The main reason for this upgrade is that the old version doesn't display the `OVERALL_GEOMEAN` when comparing two benchmarks.

Upgrade the version of google benchmark

---

src/ftxui/dom/benchmark_test.cpp

The benchmarks were only doing a render but not calling the ToString() method (as done in the Screen:Print method). I added this.
This allows us to see the performance improvement in https://github.com/ArthurSonzogni/FTXUI/pull/704.

Added the print stage to the benchmarks

---

README.md

Since I developed `rw-tui` using FTXUI, I want to add it to the `README.md`.
This utility was created as a TUI application for Linux with reference to RWEverything.
**Features supported:**
- Output the memory area as a table and change the value
- Output configuration space MMIO area of PCI device as table
- PCI configuration space output

Added rw-tui to the list of projects that are using FTXUI

---

include/ftxui/util/ref.hpp
src/ftxui/component/input.cpp
src/ftxui/dom/canvas.cpp

I was a bit confused by the current implementation of the ConstRef<T> and Ref<T> classes, so I decided to see if I could clarify your original intent.
I hated to "mess up" the simplicity of the original classes, but I think I've codified what you were trying to do.
I'm hoping you will find this useful enough to merge into your repo.

Possible clarification and reimplementation of Ref<T> classes

---

src/ftxui/screen/color.cpp

-Wshadow would warn on shadowed local variables
in the Color::Interpolate function

Fix Wshadow warning in Color::Interpolate

---

CHANGELOG.md
include/ftxui/component/screen_interactive.hpp
src/ftxui/component/screen_interactive.cpp

When mouse events are enabled, it is not possible to select text in the terminal and copy it somewhere else. This could be usefull for some applications if they don't need to handle mouse events.
Add a function on the ScreenInteractive class to disable grabbing of mouse events so that it is e.g. possible to select text in the user interface. The function needs to be called on the screen object before starting the application loop if such a behaviour is desired.

Add a DisableMouseEvents() on ScreenInteractive to disable mouse events

---

include/ftxui/util/ref.hpp
src/ftxui/dom/canvas.cpp

Here is a slight improvement in the handling of the construction of those two classes.
It uses a pass-by-value-when-moving type of approach.  This will handle both L-values and R-values cleanly.  Of course, this assumes that moves are free (which they typically are) and are inlined.
What do you think?
P.S. Yes, I meant "reseatable" and not "resetable".  :)

Tidy up some ConstRef<T> and Ref<T> constructor cases

---

cmake/ftxui_set_options.cmake
src/ftxui/component/container.cpp
src/ftxui/component/terminal_input_parser.cpp

Add the -Wuseless-cast to the FTXUI_DEV_WARNINGS and fix the compiler complaints about useless casts

Add -Wuseless-cast to FTXUI_DEV_WARNINGS

---

CHANGELOG.md
cmake/ftxui_test.cmake
src/ftxui/screen/util.hpp

Add missing include guard.
This fix https://github.com/cpp-best-practices/cmake_template/issues/64

Fix CMAKE_UNITY_BUILD usage

---

README.md

Hi, I've written a simple grid container using Horizontal and Vertical Containers. But I think this should be put into the container.cpp instead of a different library. Which one would you prefer? Thank you.

a grid container

---

src/ftxui/dom/scroll_indicator.cpp
src/ftxui/dom/scroll_indicator_test.cpp

Hi there,
This a proposed MR to fix #754. While building the scroll bar the pixels were completely reseted thus canceling any style previously applied to said pixels. This MR removes this resetting of the pixels and leaves only the drawing of the shape of the scroll bar.

Scrollbar coloring

---

flake.lock
flake.nix

We update the lock on the nix flake and also add a dev shell. This means you can do `nix build` to build the project and `nix develop` to drop into a development environment with cmake and clang.

update nix and add dev shell

---

CHANGELOG.md
src/ftxui/component/input.cpp

I noticed that the `on_change` callback for the `Input()` component is not called when backspace or delete keys are pressed. This PR fixes that.

Input onchange not called

---

cmake/ftxui_set_options.cmake

This pr aims to fix the problem discussed in [this issue](https://github.com/ArthurSonzogni/FTXUI/issues/801).

ftxui_set_options: properly check the current compiler.

---

src/ftxui/component/button.cpp

Some users might destroy `this`, which would result in UAF.
In the future, we should consider alternatives like posting a task to the main loop, or rely on users for this.
Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/804

Button: invoke `on_click` at the end.

---

src/ftxui/component/checkbox.cpp

Interacting with a component is a strong indicator of focus, so clicking a checkbox should cause it to take focus. This also allows keyboard input to toggle a checkbox after clicking it. (#798)

Make Checkbox take focus when clicked

---

examples/component/homescreen.cpp

- Currently there is no clean way to exit an example (we need to press ctrl + c to do so)
- Added a exit button in the homescreen example to propose a cleaner way to exit the execution.

Feature: adding exit button in the homescreen example

---

CHANGELOG.md
src/ftxui/component/resizable_split.cpp
src/ftxui/component/resizable_split_test.cpp

example:
```cpp
auto focusableText = [] {
return Renderer([](bool focused) {
if (focused) {
return text("focused!") | focus;
} else {
return text("not focused");
}
});
};
int top_size = 1;
screen.Loop(ResizableSplitTop(focusableText(), focusableText(), &top_size));
```
output:
```
focused!
--------------
not focused
```
Expected behavior: The text changes when I press up/down keys.
Actual behavior: The text changes when I press left/right keys.
I think this is because ResizableSplit internally uses Container::Horizontal regardless of its direction option, so I fixed it to use correct container.

Fix ResizableSplit handling keyboard navigation incorrectly

---

src/ftxui/component/screen_interactive.cpp

This avoids an ordering problem with whatever the user printed and interacting with termios/WinAPI.
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/846

Flush before applying a new configuration.

---

CHANGELOG.md
examples/component/print_key_press.cpp
include/ftxui/component/event.hpp
include/ftxui/component/mouse.hpp
include/ftxui/component/screen_interactive.hpp
include/ftxui/dom/canvas.hpp
include/ftxui/screen/screen.hpp
src/ftxui/component/event.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/component/screen_interactive_test.cpp
src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser_test.cpp
src/ftxui/dom/canvas.cpp
src/ftxui/screen/image.cpp
src/ftxui/screen/screen.cpp

In order for applications to receive all keyboard inputs, including the Ctrl-C and Ctrl-Z, the raw input mode has been enabled.
As result the SIGINT will no longer be used, instead the keyboard Ctrl-C event is used for exiting the framework, but only if no components has made use of it.

Enable raw keyboard input

---

CMakeLists.txt
include/ftxui/component/animation.hpp
include/ftxui/component/captured_mouse.hpp
include/ftxui/component/component.hpp
include/ftxui/component/component_base.hpp
include/ftxui/component/loop.hpp
include/ftxui/component/receiver.hpp
include/ftxui/dom/elements.hpp
include/ftxui/dom/node.hpp
include/ftxui/dom/table.hpp
include/ftxui/dom/take_any_args.hpp
include/ftxui/screen/color.hpp
include/ftxui/screen/string.hpp
include/ftxui/util/autoreset.hpp
include/ftxui/util/ref.hpp
src/ftxui/component/component_fuzzer.cpp
src/ftxui/dom/box_helper.hpp
src/ftxui/dom/flexbox_helper.hpp
src/ftxui/dom/node_decorator.hpp
src/ftxui/screen/string_internal.hpp
src/ftxui/screen/util.hpp

Fix all the diagnostics reported.
Bug: https://github.com/ArthurSonzogni/FTXUI/issues/828

Generate compile commands for clangd.

---

CHANGELOG.md
cmake/ftxui_test.cmake
include/ftxui/util/ref.hpp
src/ftxui/util/ref_test.cpp

Bug:https://github.com/ArthurSonzogni/FTXUI/issues/843

Add ConstStringListRef Adapter.

---

include/ftxui/component/screen_interactive.hpp

Found a small issue when playing around with making bazel build file for this repo, I could make a pull for that as well if you wish.

Solve issues with atomic copy

---

README.md

I am currently working on [ostree-tui](https://github.com/AP-Sensing/ostree-tui), a **TUI** for **OSTree** (a Version Control System for operating system binaries). It makes use of this awesome TUI library and I would love to add it to the **FTXUI project list**.
I couldn't determine any order of the listed projects, which is why I suggest putting the [ostree-tui](https://github.com/AP-Sensing/ostree-tui) right under the [git-tui](https://github.com/ArthurSonzogni/git-tui), as they are very similar projects (in the sense that both are built for supporting the user in handling a VCS).

Add ostree-tui to README

---

cmake/ftxui_set_options.cmake

Without this, a shared object containing FTXUI code won't work. This is only needed on Unix.

Added -fPIC compile option on UNIX

---

include/ftxui/dom/table.hpp
src/ftxui/dom/table.cpp
src/ftxui/dom/table_test.cpp

To avoid burdening the user with explicit type construction when using the library, we can use a constructor that accepts an initializer list (std::initializer_list). This allows users to pass initializer lists directly without having to wrap them in
std::vector<std::vector<std::string>>. This resolves the ambiguous case when the inner list contains only two elements.
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/912

Table: support initializer list constructor.

---

README.md

issue: [Add an image display component](https://github.com/ArthurSonzogni/FTXUI/issues/782)
Hi, I've tried to add an [image display component](https://github.com/ljrrjl/ftxui-image-view) to FTXUI, at the moment the efficiency and functionality of this component is not perfect, I'll try to improve it later on.

add ftxui-image-view for image display

---

CHANGELOG.md
include/ftxui/component/component_base.hpp
include/ftxui/component/component_options.hpp
src/ftxui/component/button.cpp
src/ftxui/component/checkbox.cpp
src/ftxui/component/component.cpp
src/ftxui/component/menu.cpp
src/ftxui/component/menu_test.cpp
src/ftxui/component/radiobox.cpp

Change to enable checking item index via MenuEntryOption.transform, so custom code can fetch data instead of relying on label string.
Note the index lookup via parent in MenuEntry.

Add index to EntryState

---

CHANGELOG.md
include/ftxui/component/component_options.hpp
src/ftxui/component/slider.cpp
src/ftxui/component/slider_test.cpp

I wanted to do some actions in real time when the slider value changes, not only update the reference value, so I made a little `SliderWithCallback` component

Add `SliderWithCallback` component

---

CHANGELOG.md
examples/dom/table.cpp
include/ftxui/dom/elements.hpp
src/ftxui/dom/util.cpp

For long tables (and other DOM elements), one may want the screen to render on dimensions higher than the terminal.  
Hence, this PR proposes a way to do so, with an optional parameter in the `Dimension::Fit` util function.
Discussions / Issues :  
* https://github.com/ArthurSonzogni/FTXUI/issues/572
* https://github.com/ArthurSonzogni/FTXUI/discussions/949

Allow a Dimension::Fit to extend beyond the terminal maximum height

---

src/ftxui/dom/border.cpp

Seems like the documentation [site](https://arthursonzogni.github.io/FTXUI/namespaceftxui.html#aa074cdab57eeb47b99f1699bcc8addd8) has this as a minor typo.

Fix typo borderLight and borderDashed

---

src/ftxui/dom/border.cpp

Just change this
```cpp
title_box.x_max = box.x_max - 1;
```
to this
```cpp
title_box.x_max = std::min(box.x_max - 1, box.x_min + children_[1]->requirement().min_x);
```

Fix: Properly changing window title text color #940

---

examples/index.mjs

After installing the service worker to use the COOP/COEP header, ensure the document is reloaded.
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/973 Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/973

Force reload in examples.

---

README.md

I made these two projects a while ago, but recently ported `keywords` to WebAssembly and realised that I hadn't added them to FTXUI's `README.md`.
The WebAssembly version of `keywords` is available [here](https://oakamoore.itch.io/keywords).

Add `terminal-rain` and `keywords` to `README.md`

---

.github/workflows/build.yaml
CHANGELOG.md
src/ftxui/dom/focus.cpp
src/ftxui/dom/node.cpp

A patch handling focus was recently merged, but a special condition on Windows was inverted, causing a segfault.
Bug:https://github.com/ArthurSonzogni/FTXUI/issues/1020

Window: Major crash fix.

---

CHANGELOG.md
src/ftxui/component/resizable_split.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/size.cpp

Component
---------
- Bugfix: Fix a crash with ResizeableSplit. See #1023.
- Clamp screen size to terminal size.
- Disallow `ResizeableSplit` with negative size.
Dom
---
- Bugfix: Disallow specifying a negative size constraint. See #1023.
Bug: https://github.com/ArthurSonzogni/FTXUI/issues/1023

Bugfix: Avoid crash with ResizeableSplit.

---

CHANGELOG.md
CMakeLists.txt
MODULE.bazel
README.md

This highlight support for the Bazel build system.

Release version 6.1.0.

---

src/ftxui/component/button.cpp

The `ButtonBase` class inherits from `ButtonOption` but also had a private `option_` member of the same type. This member was redundant and unused.
This PR removes the unnecessary member to clean up the code and slightly reduce the object's memory footprint.

Remove redundant member from ButtonBase

---

cmake/ftxui_modules.cmake
doc/cpp20-modules.md

Just a quick change to go ahead and enable the umbrella module discussed in issue #1083.
I want this PR to be minimal, but would think a nice follow-on PR would be to add an example or at least test for the `import ftxui;` case, or change the current module edit script to use it instead of the individual modules.

Add ftxui convenience/umbrella module to cmake rules to fix #1083

---

include/ftxui/screen/screen.hpp

The cursor_ variable was being default initialized, which causes undefined behaviour when accessing properties in
ScreenInteractive::Draw. This caused a crash when running with UBSAN.
```
ftxui/src/ftxui/component/screen_interactive.cpp:852:17: runtime error:
load of value 4195502944, which is not a valid value for type 'Shape'
```
This change causes cursor_ to be value initialized so that its members will be initialized to 0.

Fix use of uninitialized cursor variable

---

cmake/ftxui_install.cmake

The `install(TARGETS ...)` command in `cmake/ftxui_install.cmake` was missing required destination specifications that became mandatory in CMake 3.12+. This caused build failures when users tried to install FTXUI with the minimum supported CMake version.
The issue occurred because the install command:
```cmake
install(
TARGETS screen dom component
EXPORT ftxui-targets
)
```
Was missing explicit destination specifications for different artifact types. CMake 3.12+ requires these destinations to be explicitly declared.
This PR adds the required destination specifications:
```cmake
install(
TARGETS screen dom component
EXPORT ftxui-targets
ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
)
```
The fix …

Fix CMake 3.12 compatibility by adding required install destinations

---

README.md

I'm new to FTXUI and was trying to build using Bazel by following the instructions in the README.md file. I would get some errors and couldn't get it to compile successfully.
After some while, I found that the instructions on the  [website](https://arthursonzogni.github.io/FTXUI/installation_bazel.html) are different and worked for me.
This PR updates the Bazel usage section in the README.md to match the correct and working example from the website.

Updated bazel build example section in README
