ArthurSonzogni/FTXUI

CMakeLists.txt

Features:
- ~~Automatic indexing of source files for each library~~
- Exported targets for easy use as git sub-module or with projects like [CPM.cmake](https://github.com/TheLartians/CPM.cmake)
- Options to exclude unwanted build targets
I tested this file and it is backwards compatible with the old one.

CMakeLists.txt rewrite

---

src/ftxui/component/screen_interactive.cpp

Read all the input before drawing anything on the screen.

Improve performance.

---

include/ftxui/component/toggle.hpp
src/ftxui/component/toggle.cpp
src/ftxui/component/toggle_test.cpp

Added on_enter method to toggle component, and test cases for the same

---

CMakeLists.txt

Fix: https://github.com/ArthurSonzogni/FTXUI/issues/62

Fix CMake when git is not found.

---

src/ftxui/screen/terminal.cpp

There was many obvious bugs, discovered here:
https://github.com/Gusabary/SAIL/blob/ad2a085469d80cfdcccd13abc5efcbabf1154cd4/Open-Source-Project-Anatomy/FTXUI.md

Fix terminal color detection support.

---

src/ftxui/screen/color.cpp

On terminal not supporting some color palette, fallback toward the closest one.

Color fallback

---

CMakeLists.txt
include/ftxui/component/event.hpp
src/ftxui/component/event.cpp
src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp

Added few events, mainly to improve input component.

Added Home, End, PgUp, PgDown events. Added handling for Home and End events for input component

---

CMakeLists.txt

This may resolve:
https://github.com/ArthurSonzogni/FTXUI/issues/89

Build the libraries statically.

---

CMakeLists.txt
include/ftxui/dom/node.hpp
src/ftxui/component/radiobox.cpp
src/ftxui/component/terminal_input_parser.hpp
src/ftxui/dom/border.cpp
src/ftxui/dom/dbox.cpp
src/ftxui/dom/flex.cpp
src/ftxui/dom/frame.cpp
src/ftxui/dom/hbox.cpp
src/ftxui/dom/hflow.cpp
src/ftxui/dom/node.cpp
src/ftxui/dom/node_decorator.cpp
src/ftxui/dom/reflect.cpp
src/ftxui/dom/separator.cpp
src/ftxui/dom/size.cpp
src/ftxui/dom/vbox.cpp

Requested here:
https://github.com/robinlinden/hastur/pull/12

Pass -Wshadow

---

src/ftxui/dom/separator.cpp

separator() should modify only the character, not the background color.

Fix separator()

---

CMakeLists.txt
src/ftxui/component/screen_interactive.cpp
src/ftxui/component/screen_interactive_test.cpp

This fixes:
https://github.com/ArthurSonzogni/FTXUI/issues/117

Do not throw SIGINT after catching SIGINT signal

---

examples/dom/color_gallery.cpp
src/ftxui/component/component_test.cpp
src/ftxui/component/terminal_input_parser.cpp

This should solve issue:
https://github.com/ArthurSonzogni/FTXUI/issues/149

Resolve compile error on cygwin.

---

examples/component/input.cpp
include/ftxui/component/component_options.hpp
include/ftxui/screen/screen.hpp
src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp

This fixes:
https://github.com/ArthurSonzogni/FTXUI/issues/139
CC:@Creapermann

Add support for password for input element.

---

.github/workflows/documentation.yaml

Install graphviz to let Doxygen generate graph.

---

README.md

Update the link in the README.md. Use the auto-deployed documentations
and examples @tusharpm made.

Update link from README.md

---

include/ftxui/component/component_base.hpp
src/ftxui/component/button.cpp
src/ftxui/component/checkbox.cpp
src/ftxui/component/component.cpp
src/ftxui/component/container.cpp
src/ftxui/component/container_test.cpp
src/ftxui/component/input.cpp
src/ftxui/component/menu.cpp
src/ftxui/component/radiobox.cpp
src/ftxui/component/slider.cpp
src/ftxui/component/toggle.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/167

Add non focusable components.

---

include/ftxui/screen/box.hpp
src/ftxui/component/renderer.cpp

@tusharpm let two comments in:
https://github.com/ArthurSonzogni/FTXUI/pull/175
but this already landed in:
https://github.com/ArthurSonzogni/FTXUI/pull/173
Address them here.

Address @tusharpm comments.

---

CMakeLists.txt
src/ftxui/dom/box_helper.cpp
src/ftxui/dom/box_helper.hpp
src/ftxui/dom/hbox.cpp
src/ftxui/dom/vbox.cpp

This reverts commit a7095970bca991c22573d7bfd241d272b4376d76.

Reland "Factorize box layout functions. (#185)""

---

README.md

TimeAccumulator was added as a project using FTXUI lib.

Added TimeAccumulator in README.md

---

CHANGELOG.md
CMakeLists.txt

- Increase version to 0.9
- Add a changelog.
From now one. Developpement happens on the `dev` branch.
See: https://github.com/ArthurSonzogni/FTXUI/discussions/207

Add Changelog.

---

.github/workflows/release.yaml

This will let me time to add a description.

Submit release as draft.

---

CHANGELOG.md
examples/component/checkbox.cpp
src/ftxui/component/input.cpp
src/ftxui/dom/blink.cpp

This fixes:
https://github.com/ArthurSonzogni/FTXUI/issues/252

Input shouldn't take focus.

---

src/ftxui/dom/gridbox.cpp
src/ftxui/dom/gridbox_test.cpp

Fix gridbox segfault

---

README.md

Thanks for making this library, it was fun to use. There are some features I want, but overall i could get things working relatively painlessly.

adding tabdeeli as a project using ftxui

---

include/ftxui/dom/canvas.hpp

Reduce amount of warnings with pedantic compiler

---

src/ftxui/screen/terminal.cpp

1. the default window size should be 80x24 rather than 80x25 in VT100.
2. the ioctl return value result should be checked. Some operating systems don't support TIOCGWINSZ this command.

improve the window size handle method

---

README.md

Add tusharpm/tiles in README

---

CHANGELOG.md
CMakeLists.txt
examples/component/focus.cpp
examples/component/with_restored_io.cpp
examples/dom/color_info_sorted_2d.ipp
include/ftxui/component/event.hpp
include/ftxui/component/screen_interactive.hpp
include/ftxui/component/task.hpp
src/ftxui/component/component_fuzzer.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser.hpp
src/ftxui/component/terminal_input_parser_test.cpp
src/ftxui/component/terminal_input_parser_test_fuzzer.cpp

- Add support for SIGTSTP:
https://github.com/ArthurSonzogni/FTXUI/issues/330
This
- Add support for task posting.
This allows folks to defer function execution, and execute it directly
below the main loop. The task are executed in a FIFO order.

Support SIGTSTP and task posting.

---

CHANGELOG.md
src/ftxui/component/event.cpp
src/ftxui/component/terminal_input_parser.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/337

Convert \r into \n

---

src/ftxui/component/collapsible.cpp

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

component/collapsible: drop unused member variable

---

examples/component/canvas_animated.cpp
include/ftxui/component/screen_interactive.hpp
src/ftxui/component/menu.cpp
src/ftxui/component/screen_interactive.cpp

- Do not draw more frames than what is needed.
- Fix MenuEntry transform state.
- Fix Canvas animated example.

Bug fixes.

---

CHANGELOG.md
examples/component/CMakeLists.txt
examples/component/button_in_frame.cpp
src/ftxui/component/button.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/370

Make the focused button to take the focus inside frame.

---

src/ftxui/component/screen_interactive.cpp
src/ftxui/component/screen_interactive_test.cpp

Fix segfault when PostEvent() called on inactive screen.

Fix PostEvent() segfault

---

CHANGELOG.md
src/ftxui/dom/flexbox_test.cpp
src/ftxui/dom/frame.cpp
src/ftxui/dom/gridbox.cpp
src/ftxui/dom/gridbox_test.cpp

This was discovered in:
https://github.com/ArthurSonzogni/FTXUI/issues/407

Fix gridbox selected box

---

README.md

https://github.com/SAtacker/beagle-config

Add beagle-config into the project list

---

README.md

https://github.com/DanArmor/turing_cmd

Add turing_cmd into the project list

---

README.md

Add StartUp into the project list
[StartUp](https://github.com/StubbornVegeta/StartUp)

Add StartUp into the project list

---

cmake/iwyu.cmake

Typo in iwyu.cmake

---

CHANGELOG.md
include/ftxui/component/component.hpp
include/ftxui/util/ref.hpp
src/ftxui/component/slider.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/456

Add ref for sliders.

---

CHANGELOG.md
src/ftxui/component/menu.cpp
src/ftxui/component/slider.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/453

Menu: keep the previously focused element with mouse.

---

CHANGELOG.md
examples/index.html
src/ftxui/component/screen_interactive.cpp
src/ftxui/screen/terminal.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/432

Add support for emscripten screen resize.

---

CHANGELOG.md
src/ftxui/component/component_options.cpp

It was missing. See:
https://github.com/ArthurSonzogni/FTXUI/issues/471

Implement ButtonOption::Border()

---

src/ftxui/dom/util.cpp

Using a static code analyzer, a suspicious place was discovered. I've fixed it.

FIX: minor mistake

---

src/ftxui/component/radiobox_test.cpp

See: https://github.com/ArthurSonzogni/FTXUI/pull/491#issuecomment-1264335576

Test Page{Up,Down} for Radiobox.

---

src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser_test.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/508
Apparently, this is a common issue:
https://www.cs.colostate.edu/~mcrob/toolbox/unix/keyboard.html

Interpret 8 as 127

---

src/ftxui/dom/table_test.cpp
src/ftxui/screen/screen.cpp

I noticed an issue with automerging at top and left borders of the screen. Here is proposed fix with a testcase. Hope you can use this. Thanks for an awesome library.

Fix automerge at border

---

src/ftxui/component/animation_test.cpp
src/ftxui/component/loop.cpp
src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/frame.cpp
src/ftxui/screen/string.cpp
src/ftxui/screen/string_test.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/514

Remove codecvt dependency.

---

CHANGELOG.md
CMakeLists.txt
cmake/ftxui_test.cmake
include/ftxui/component/component.hpp
src/ftxui/component/hoverable.cpp
src/ftxui/component/hoverable_test.cpp

This will make it easier for developers.
For instance: https://github.com/ArthurSonzogni/FTXUI/issues/521

Add the Hoverable wrapper.

---

src/ftxui/component/screen_interactive.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/523

Fix mouse on support over PuTTY

---

include/ftxui/component/component.hpp
src/ftxui/component/slider.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/524

Add all the Slider implementations.

---

src/ftxui/component/slider.cpp
src/ftxui/component/slider_test.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/547
From discussion:
https://github.com/ArthurSonzogni/FTXUI/discussions/546

Fix slider focus.

---

cmake/ftxui_fuzzer.cmake

Previous patch introduced a regression. The condition needs to be inverted.
Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/556

Fix build about fuzzer.

---

src/ftxui/component/screen_interactive.cpp

This resolves:
https://github.com/ArthurSonzogni/FTXUI/issues/559

Fix: cursor position offset.

---

CHANGELOG.md
src/ftxui/dom/scroll_indicator.cpp
src/ftxui/dom/scroll_indicator_test.cpp

This resolve:
https://github.com/ArthurSonzogni/FTXUI/issues/574

Fix vscroll hidding the last character.

---

doc/mainpage.md

Corresponding PR for #584.
Again, this is my first PR so let me know if my process is incorrect. Thanks!

Reword description of ftxui/component in #modules

---

src/ftxui/component/screen_interactive.cpp
src/ftxui/dom/flexbox_helper.cpp

Fix Apple Clang 14 build errors

---

src/ftxui/component/dropdown.cpp
src/ftxui/component/resizable_split.cpp
src/ftxui/dom/frame.cpp
src/ftxui/dom/scroll_indicator.cpp

Taken out of:
https://github.com/ArthurSonzogni/FTXUI/pull/600

nit: Remove useless ';' and ','

---

include/ftxui/component/animation.hpp
src/ftxui/component/animation.cpp

Partially taken out of:
https://github.com/ArthurSonzogni/FTXUI/pull/600

Update float style in animation.cpp

---

CHANGELOG.md
src/ftxui/component/screen_interactive.cpp

Fix:https://github.com/ArthurSonzogni/FTXUI/issues/609

Fix useless new line when using the alternative screen.

---

.github/workflows/build.yaml

This fixes:
https://github.com/ArthurSonzogni/FTXUI/issues/599

Update workflow to main branch.

---

src/ftxui/dom/graph.cpp

Bug:https://github.com/ArthurSonzogni/FTXUI/issues/624

Check graph area is positive.

---

src/ftxui/component/input.cpp
src/ftxui/component/input_test.cpp

Fixed:https://github.com/ArthurSonzogni/FTXUI/issues/666

Fix on_enter bug in ftxui::Input

---

CHANGELOG.md
src/ftxui/component/terminal_input_parser.cpp
src/ftxui/component/terminal_input_parser_test.cpp

Bug:https://github.com/ArthurSonzogni/FTXUI/issues/685

Support F1-F5 from OS terminal

---

src/ftxui/component/dropdown.cpp

Hi, this is my first time doing pull request! I think it would be nice if the dropdown menu closes after selecting an entry. Please tell me if I'm doing anything wrong. Thank you!

Dropdown now closes when using return key to select

---

README.md
examples/component/button.cpp

Hi @tzzzzzzzx,
I found your repository, would you like it to be listed on the FTXUI page?

List ftxui_CPUMeter

---

README.md

Hi @J0sephDavis,
I would like to list your repository into the FTXUI one. What do you think?

List J0sephDavis/ftxuiFileReader

---

examples/component/button.cpp

I noticed that there are 2 buttons labeled '-10', but one of them increases by 10.

Example: fix small flaw in example/button.cpp

---

CHANGELOG.md
include/ftxui/component/screen_interactive.hpp
src/ftxui/component/screen_interactive.cpp

This should solve #766 
The original PR was:
https://github.com/ArthurSonzogni/FTXUI/pull/767

feat: allow fullscreen without alternative screen

---

README.md

Add "Captain's log" (`caps-log`) to the list of projects using FTXUI library.

Add Captain's log to README

---

README.md

FTowerX is Tower of Hanoi game developed using FTXUI

Add FTowerX to README

---

examples/component/button.cpp

It was introduced mistakenly by:
https://github.com/ArthurSonzogni/FTXUI/commit/f495ce029cb3a9b4c8309e4456e494f8b6b09967

Revert change to button example.

---

README.md

clarified some sentences, changed "external package" section to "utilization", added a tip on linking for a trouble I ran into

clarified README and added tip on linking

---

src/ftxui/component/screen_interactive.cpp

PR for proposed change from #846

improving sigint handling

---

include/ftxui/dom/elements.hpp
src/ftxui/dom/border.cpp

It'd be neat to allow the window element to have different border styles.

Allow user to specify window element border.

---

CHANGELOG.md
src/ftxui/component/menu.cpp

Bug:https://github.com/ArthurSonzogni/FTXUI/issues/841

Fix `Menu` focus.

---

CMakeLists.txt
include/ftxui/component/animation.hpp
include/ftxui/component/captured_mouse.hpp
include/ftxui/component/component.hpp
include/ftxui/component/component_base.hpp
include/ftxui/component/loop.hpp
include/ftxui/component/receiver.hpp
include/ftxui/dom/elements.hpp
include/ftxui/dom/node.hpp
include/ftxui/dom/table.hpp
include/ftxui/dom/take_any_args.hpp
include/ftxui/screen/color.hpp
include/ftxui/screen/string.hpp
include/ftxui/util/autoreset.hpp
include/ftxui/util/ref.hpp
src/ftxui/component/component_fuzzer.cpp
src/ftxui/dom/box_helper.hpp
src/ftxui/dom/flexbox_helper.hpp
src/ftxui/dom/node_decorator.hpp
src/ftxui/screen/string_internal.hpp
src/ftxui/screen/util.hpp

Fix all the diagnostics reported.
Bug: https://github.com/ArthurSonzogni/FTXUI/issues/828

Generate compile commands for clangd.

---

README.md

Hey @ArthurSonzogni,
I had a great time rewriting my project around FTXUI. Would it be okay if I included it in your README?
Best wishes, r3w0p.

Added Caravan to README.md

---

examples/component/button.cpp

Hi!I find a small bug in the exapmle (button.cpp).

fix a small bug in button example

---

README.md

We use FTXUI as the frontend for the example C++ application for our adaptive music runtime engine.
https://github.com/xjmusic/xjmusic/tree/main/engine/example

Add XJ music to FTXUI example projects

---

README.md

I implement the 2048 game using FTXUI. This library is really powerful and amazing!

Add 2048-cpp to projects using FTXUI

---

README.md

Great work and very cool library !

Adding BestEdrOfTheMarket to project examples

---

README.md

Hello, I have developed a terminal file browser using FTXUI, which is suitable for the Linux platform.
This is link [https://github.com/Cyxuan0311/FTB.git](url)

Add a new example in README.md

---

src/ftxui/dom/node.cpp

See: https://github.com/ArthurSonzogni/FTXUI/pull/1021?notification_referrer_id=NT_kwDOAEieQrMxNTU3OTg4MDA1MDo0NzU5MTA2#discussion_r2019827970

Apply @forworldm code review.

---

README.md

_SHOOT!_ is a text-based game written for a university course project. It relies heavily on FTXUI for its UI and gameplay.

Adds example project using FTXUI

---

README.md

Fix `Examples` (from `README.md`) section link

---

README.md

Library was easy to use. Thank you :)

Add new project to the list

---

doc/installation_conan.md

I've written a guide for the installation method via Conan. Although there might be some errors in what I've written—likely due to connectivity issues since I'm located in China (the error messages indicate connection failures)—I do have a verified version that works, even though it's a bit more cumbersome. I hope the format of what I've written is correct and can be helpful.

Improved the installation method via Conan.

---

src/ftxui/dom/size.cpp

fixed a typo

---

README.md

Thank you, it was a wonderful experience using this library.

Add tic-tac-toe as an example project using FTXUI
